---
title: "housing"
author: "Evan Odell"
date: "1 November 2017"
output: html_document
---


## About this Map

I've created this app in response to a request from [Mark Butcher](https://twitter.com/butcher_sl) to highlight specific areas of London with properties offering good value-for-money, relative to their transport accessibility. It is based on a [blog post](https://evanodell.com/blog/2017/10/20/housing-prices-and-transport-accessibility/) I wrote last month that looked at the general relation between price and transport accessibility. Green offers the highest value for money (what I've called bang for buck), while red is the lowest, based on transport accessibility in the local area, the absolute price of the property and the price-per-room.

Central London properties appear to offer the best value-for-money, provided you have the millions of pounds available to buy one. This is a consequence of both the incredibly high levels of transport accessibility and the apparent size of properties. The price per room of luxury flats in Kensington is much higher than the price-per-room of ex-council flats in Bethnal Green, as is the absolute price, but the transport accessibility scores are incredibly high compared to even other well-connected areas. The practical difference between a bus every 2 minutes and a bus every 3 minutes is unlikely to be very noticable.

## Methodology

This map combines HM Land Registry's price paid data from September 2012 -- August 2017 with the [PTAL scores](https://data.london.gov.uk/dataset/public-transport-accessibility-levels) produced by TFL, which show how connected to public transport a given area is, in this case Lower Layer Super Output Areas (LSOA).

Housing is divided into four types: flats, terraced houses, semi-detached houses and detached houses. Only one kind of housing can be displayed at a time. You can also subdivide by TFL travel zone and PTAL level, and put a maximum price on properties.

### Estimating Rooms in a Property

The census data I used has the average number of rooms in a property in each LSOA, as well as the type of house, but does not break down property size by house type. I used linear regressions between the average number of rooms in each household and the percentage of properties in each housing type to predict the average number of rooms per housing type in each area. 

The price-per-room is an important variable in the bang for buck algorithm, and represents the amount of housing and space available in the property. It does not take account of the size of these rooms or of the property as a whole, quality of construction, or features such as a garden or balcony. From the [dataset description](https://www.nomisweb.co.uk/census/2011/dc4404ew.pdf): 

> The definition of a room does not include bathrooms, toilets, halls or landings, or rooms that can only be used for storage. All other rooms, for example, kitchens, living rooms, bedrooms, utility rooms, studies and conservatories are counted. If two rooms have been converted into one they are counted as one room. Rooms shared between a number of households, for example a shared kitchen, are not counted.

This means that open plan properties are be given a higher price per room; e.g. a combined kitchen-dining room-living room counts as one single room, whereas they could be three different rooms in another property.


### Bang for Buck Score

The bang for buck score is the percentile (range of 0 to 1) of the scaled (range of 0 to 1) PTAL score multiplied by the inverse scaled (range of -1 to 1) estimated price-per-room, and the inverse scaled (range of -1 to 0) price. The score is calculated based on all areas included in the data; e.g. including only zone 1 will produce scores relative to all other properties in zone 1.


### Source Code

Source code for this app and prepatory work is available on [GitHub](https://github.com/evanodell/house-price-ptal). Code is available under an [MIT license](https://github.com/evanodell/house-price-ptal/blob/master/LICENSE).

### Data Sources

Data has been taken from the ONS, the London Data Store and HM Land Registry. [Price paid data](https://www.gov.uk/government/statistical-data-sets/price-paid-data-downloads) is made available under the [Open Government Licence v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), [PTAL data](https://data.london.gov.uk/dataset/public-transport-accessibility-levels), the [London shapefile](https://data.london.gov.uk/dataset/2011-boundary-files) and the [My London data](https://data.london.gov.uk/dataset/mylondon) are available under the [Open Government Licence v2.0](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/). Key census statistics are taken from [Nomis](https://www.nomisweb.co.uk/census/2011/key_statistics).


Going forward, I plan to incorporate additional variables into the bang for buck algorithm, including local crime rates, levels of deprivation, commuting times to central London, etc. If you have any requests or suggestiosn, spot any issues with the data, or anything else, you can [email me](mailto:evanodell91@gmail.com), or raise an issue on [GitHub](https://github.com/evanodell/house-price-ptal/issues).
